// 应用图标导出
// 用法：import { feishuIcon, wecomIcon } from '@/assets/icons/apps'

export { default as feishuIcon } from './feishu.svg'
export { default as wecomIcon } from './wecom.svg'
export { default as weiboIcon } from './weibo.svg'
export { default as notificationIcon } from './notification.svg'
export { default as douyinIcon } from './douyin.svg'
export { default as bilibiliIcon } from './bilibili.svg'
export { default as zhihuIcon } from './zhihu.svg'
export { default as toutiaoIcon } from './toutiao.svg'
export { default as doubanIcon } from './douban.svg'
export { default as kuaishouIcon } from './kuaishou.svg'
export { default as javaScriptIcon } from './javaScript.svg'
export { default as openaiIcon } from './openai.svg'
