// 文件资源菜单权限 key
const FILE_RESOURCE_MENU_KEY = "resource.file-resource";

export interface MenuAccessOption {
  key: string;
  label: string;
  adminOnly?: boolean;
  legacyKeys?: string[];
}

export interface MenuAccessGroup {
  label: string;
  options: MenuAccessOption[];
}

export const ADMIN_ONLY_MENU_KEYS = new Set([
  "system.user",
  "system.company",
  "system.role",
  "system.websocket",
  "system.service-file-cache",
  "system.operatelog",
  "system.file-log",
]);

export const ROUTE_MENU_KEY_MAP: Record<string, string> = {
  Index: "home.index",
  HotSearch: "home.hot-search",
  ToolsIndex: "home.tools",
  Statistics: "home.statistics",
  VectorSearch: "home.vector-search",
  DesignKnowledge: "home.design-knowledge",
  DesignPrompt: "home.design-prompt",
  CrawlerMaterial: "resource.crawler-material",
  Material: "resource.material",
  CustomSticker: "resource.custom-sticker",
  FileResource: FILE_RESOURCE_MENU_KEY,
  Asset3d: "resource.asset-3d",
  Font: "resource.font",
  Psd: "resource.psd",
  StoryScript: "resource.story-script",
  Sentence: "resource.sentence",
  TextDocument: "resource.text-document",
  DesignInspiration: "resource.design-inspiration",
  CodeScript: "content.code-script",
  CodeScriptSchedule: "content.code-script-schedule",
  RemotionVideoRecord: "content.remotion-video-record",
  ImageProcessingRecord: "content.image-processing-record",
  OperationToolkitTemu: "external.toolkit.temu",
  OperationToolkitDoudian: "external.toolkit.doudian",
  OperationToolkitPdd: "external.toolkit.pdd",
  OperationToolkitKuaishouShop: "external.toolkit.kuaishou-shop",
  OperationToolkitQianniu: "external.toolkit.qianniu",
  OperationToolkitAlibaba1688: "external.toolkit.alibaba-1688",
  OperationToolkitAmazon: "external.toolkit.amazon",
  ExternalToolkitLegacy: "external.toolkit",
  ExternalTemuLegacy: "external.toolkit.temu",
  ExternalBrowserAutomation: "external.browser-automation",
  ExternalBrowserPlugin: "external.browser-plugin",
  DesignToolConnection: "design-tool.connection",
  ExternalPsAutomation: "external.ps-automation",
  ExternalGoogleArt: "external.google-art",
  ClientManagement: "client.management",
  AiAssistant: "ai.assistant",
  AiSkills: "ai.skills",
  AiTti: "ai.tti",
  AiTts: "ai.tts",
  AiAgentConsole: "ai.agent",
  AiModelService: "ai.model-service",
  AiImageAnalysis: "ai.image-analysis",
  Prompt: "ai.prompt",
  McpConsole: "ai.mcp",
  ProductCategory: "product.category",
  ProductIndex: "product.index",
  ProductGenerationTemplate: "product.generation-template",
  PsdSet: "product.psd-set",
  PublishBindingRecords: "product.binding-records",
  DesignRequest: "product.design-request",
  PublishConfig: "product.publish-config",
  SystemQueue: "product.queue",
  EcomPlatformCollectCapabilityPage: "operation.ecom-platform-collect.capabilities",
  EcomPlatformCollectTaskPage: "operation.ecom-platform-collect.tasks",
  EcomPlatformCollectRunPage: "operation.ecom-platform-collect.runs",
  EcomPlatformCollectRawPage: "operation.ecom-platform-collect.raw-records",
  EcomSelectionAnalysisTaskPage: "operation.ecom-selection-analysis.tasks",
  EcomSelectionAnalysisRunPage: "operation.ecom-selection-analysis.runs",
  EcomSelectionAnalysisResultPage: "operation.ecom-selection-analysis.results",
  EcomSelectionSupplyMatchTaskPage: "operation.ecom-selection-supply-match.tasks",
  EcomSelectionSupplyMatchRunPage: "operation.ecom-selection-supply-match.runs",
  EcomSelectionSupplyMatchItemPage: "operation.ecom-selection-supply-match.items",
  ExtensionCollectIndex: "operation.extension-collect",
  OperationLinkNavigation: "operation.link-navigation",
  ShopIndex: "operation.shop",
  VendorIndex: "operation.vendor",
  VendorProductIndex: "operation.vendor-product",
  CommonUrlIndex: "resource.common-url",
  SystemAiApiKeyIndex: "system.ai-api-key",
  MessagePushIndex: "system.message-push",
  User: "system.user",
  Company: "system.company",
  PublicUser: "system.public-user",
  Role: "system.role",
  // PublicUserBehaviorLog: "system.public-user-behavior-log",
  IndependentSiteDesignRequest: "independent-site.design-request",
  IndependentSiteOpenDocs: "independent-site.open-docs",
  IndependentSiteUserBehaviorLog: "independent-site.user-behavior-log",
  SystemWebsocketConnections: "system.websocket",
  SystemServiceFileCache: "system.service-file-cache",
  SystemOperateLog: "system.operatelog",
  SystemFileLog: "system.file-log",
  PersonalSettings: "personal.settings",
  MyOrganization: "personal.organization",
};

export const ROUTE_MENU_LEGACY_KEY_MAP: Record<string, string[]> = {
  CustomSticker: ["resource.material"],
  OperationToolkitTemu: ["external.toolkit"],
  OperationToolkitDoudian: ["external.toolkit"],
  OperationToolkitPdd: ["external.toolkit"],
  OperationToolkitKuaishouShop: ["external.toolkit"],
  OperationToolkitQianniu: ["external.toolkit"],
  OperationToolkitAlibaba1688: ["external.toolkit"],
  OperationToolkitAmazon: ["external.toolkit"],
  EcomPlatformCollectCapabilityPage: ["operation.ecom-platform-collect"],
  EcomPlatformCollectTaskPage: ["operation.ecom-platform-collect"],
  EcomPlatformCollectRunPage: ["operation.ecom-platform-collect"],
  EcomPlatformCollectRawPage: ["operation.ecom-platform-collect"],
  EcomSelectionAnalysisTaskPage: ["operation.ecom-platform-collect"],
  EcomSelectionAnalysisRunPage: ["operation.ecom-platform-collect"],
  EcomSelectionAnalysisResultPage: ["operation.ecom-platform-collect"],
  EcomSelectionSupplyMatchTaskPage: ["operation.ecom-platform-collect"],
  EcomSelectionSupplyMatchRunPage: ["operation.ecom-platform-collect"],
  EcomSelectionSupplyMatchItemPage: ["operation.ecom-platform-collect"],
  ExtensionCollectIndex: ["operation.ecom-platform-collect"],
  VendorProductIndex: ["operation.vendor"],
};
